development:
  adapter: postgresql
  encoding: unicode
  database: gitter_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: gitter_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: gitter_production
  pool: 5
